image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install -D @playwright/test
      npx playwright install
    command: npx playwright test
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore