# .gitpod.yml
tasks:
  - name: Install Playwright and dependencies
    init: |
      npm install -D @playwright/test
      npx playwright install
    command: |
      npx playwright test
ports:
  - port: 9323
    onOpen: ignore