image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
     sudo apt-get update && sudo apt-get install -y \
        libwoff1 \
        libopus0 \
        libvpx7 \
        libgstreamer1.0-0 \
        libgstreamer-plugins-base1.0-0 \
        libflite1 \
        libharfbuzz-icu0 \
        libenchant-2-2 \
        libsecret-1-0 \
        libhyphen0 \
        libmanette-0.2-0 \
        libgles2 \
        libx264-160
      npx playwright install-deps
    command: npx playwright test
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore