image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npx playwright install --yes
      npx playwright install-deps
      npm ci
    command: npx playwright test
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore